apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: nodejs-todo
spec:
  selector:
    deployment: mongodb4-2
  ports:
    - port: 27017
      name: mongodb
      protocol: TCP
  type: ClusterIP
