apiVersion: v1
kind: Service
metadata:
  name: node2-clusterip-service-NODE2NAME
  namespace: virtualmachines
spec:
  ports:
  - port: 27017
    name: mariadb
    protocol: TCP
  - port: 22
    name: ssh
    protocol: TCP
  selector:
    todoservice: node2-NODE2NAME
  type: ClusterIP
